# https://snakemake-wrappers.readthedocs.io/en/v7.8.0/wrappers/bio/fastp.html
rule fastp_trim_short:
    input:
        sample = lambda wildcards: [
            SAMPLES_SHORT.at[wildcards.sample, 'fq1'],
            SAMPLES_SHORT.at[wildcards.sample, 'fq2']
        ]
    output:
        trimmed=[
            "results/trimmed/short/{sample}.1.fastq.gz", 
            "results/trimmed/short/{sample}.2.fastq.gz"
        ],
        unpaired1="results/trimmed/short/{sample}.u1.fastq.gz",
        unpaired2="results/trimmed/short/{sample}.u2.fastq.gz",
        failed="results/trimmed/short/{sample}.failed.fastq.gz",
        html="results/qc/short/{sample}.html",
        json="results/qc/short/{sample}.json"
    log:
        "logs/fastp/{sample}.log"
        
    threads: 4
    params:
        extra = lambda wildcards, threads: f"--thread {threads}"
    wrapper:
        "v7.1.0/bio/fastp"

#rule trim_all:
    #input:
        #expand("results/trimmed/short/{sample}.1.fastq.gz", sample=SAMPLES_SHORT.index),
        #expand("results/trimmed/short/{sample}.2.fastq.gz", sample=SAMPLES_SHORT.index),
        #expand("results/trimmed/long/{sample}.fastq.gz", sample=SAMPLES_LONG.index) if len(config["samples_long_read"])>0 else [],


rule fastplong_trim_long:
    input:
        fq = lambda wildcards: SAMPLES_LONG.at[wildcards.sample, "fq"]
    output:
        # The core 3 outputs generated by fastplong
        fq = "results/trimmed/long/{sample}.fastq.gz",
        html = "results/qc/fastplong/{sample}.html",
        json = "results/qc/fastplong/{sample}.json",
        # Optional: capture reads that failed filters
        failed = "results/qc/fastplong/{sample}_failed.fastq.gz"
    log:
        "logs/fastplong/{sample}.log"
    threads: 4  # fastplong scales very well with multi-threading
    resources:
        mem_mb = 4096
    conda:
        "../envs/fastplong.yaml"
    shell:
        """
        fastplong \
            -Q \
            -i {input.fq} \
            -o {output.fq} \
            -h {output.html} \
            -j {output.json} \
            --failed_out {output.failed} \
            -w {threads} \
            > {log} 2>&1
        """