import os
import pandas as pd

configfile: "config/config.yaml"

SAMPLES = pd.read_csv(config["samples"], index_col="sample", sep='\t')
#GROUPS = SAMPLES['group'].unique()
# print("DEBUG SAMPLES INDEX:", list(SAMPLES.index))
REF_BASENAME = "reference"
# files at the end of analysis

rule all:
	input:
		"results/phylo_tree/adenovirus_tree.png"
		
		# map
		#expand("results/filtered/{sample}_mapping.bam", sample=SAMPLES.index),
		# produce all stats
		#expand("results/stats/{sample}.stats", sample=SAMPLES.index),
		#"results/stats/merged.tsv",

		
		
		#"results/qc/multiqc_all.html" if not config["analysis_options"]["skip_fastQC"]==True else [],
		# TODO: should we execute FastQC on row data always or only prepare direct exection?
		#"results/qc/multiqc_raw.html" if not config["analysis_options"]["skip_fastQC"]==True else [],



include: "rules/bowtie.smk"
include: "rules/samtools.smk"
include: "rules/qc.smk"
include: "rules/ivar.smk"
include: "rules/minimap.smk"


rule aggregate_stats:
	input:
		list_of_stats = lambda wildcards: expand(
					"results/stats/{sample}.stats", sample=SAMPLES.index)
	output:
		"results/stats/merged.tsv"
	script:
		"scripts/merge_stats.py"

rule phylo_tree:
	input:
		"results/phylo_tree/msa.fa"
	output:
		tree = "results/phylo_tree/msa.fa.treefile"
	log:
		"logs/phylo_tree.log"
	threads: 4
	conda:
		"envs/phylo.yaml"
	shell:
		"""
        iqtree -s {input} -nt {threads} -pre results/phylo_tree/iqtree_out > {log} 2>&1
        cp results/phylo_tree/iqtree_out.treefile {output.tree}
        """

rule visualize_tree:
    input:
        rules.phylo_tree.output
    output:
        "results/phylo_tree/adenovirus_tree.png"
    conda:
        "envs/phylo.yaml"
    script:
        "scripts/visualize_tree.py"

