
#ref: "resources/reference/human_adenovirus_A.fasta"

# reference is of strain HadV-C, which is the most abundant in the samples, and has the highest coverage.
# https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_019453945.1/
ref: "resources/reference/ncbi_dataset/data/GCA_019453945.1/GCA_019453945.1_ASM1945394v1_genomic.fna"
samples: "resources/samples.tsv"

analysis_options:
  skip_trimming: "False"
  skip_fastQC: "False"
  skip_qualimap: "False"

ivar_params:
  max_depth: "60000"
  min_freq: "0.5"
  min_qual: "20"
  min_cov: "10"

variability_params:
  window_size: "100"

bowtie2_params:
  min_fragment_ln: "0"
  seed: "0"
  ref_index_dir: "results/ref_index/"

# http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf
trimmomatic_params:
  mode: "PE"
  # ILLUMINACLIP options
  adapter_file: "resources/adapters/TruSeq2-PE.fa"
  seed_mismatch: "2"
  palindrome_treshold: "30"
  simple_treshold: "10"
  min_adapter_length: "8" # default 8
  keep_both_reads: "False" #default false
  # there are other trimmers such as SLIDINGWINDOW which we don't implement


