# DISCLAIMER: This code was generated by Gemini. We wanted to inspect final plot.

# Log sink for debugging
log <- file(snakemake@log[[1]], open="wt")
sink(log)
sink(log, type="message")

library(DESeq2)
library(pheatmap)
library(matrixStats) # for rowVars

# 1. Load data (skip first comment line of featureCounts)
counts_data <- read.table(snakemake@input[["counts"]], header=TRUE, skip=1, sep="\t", row.names=1)

# 2. Isolate just the numeric count columns
count_matrix <- as.matrix(counts_data[, 6:ncol(counts_data)])

# Clean up raw names (e.g., "results.star.pe.normal_rep2.normal_rep2_aligned" -> "normal_rep2")
raw_names <- colnames(count_matrix)
clean_names <- gsub("^results\\.star\\.pe\\.(normal_rep\\d|tumor_rep\\d).*", "\\1", raw_names)

# Assign the clean names back to the matrix
colnames(count_matrix) <- clean_names
# 3. Create a minimal DESeq2 object
# (We use ~1 because we just want variance stabilization, not differential testing)
col_data <- data.frame(row.names = colnames(count_matrix), condition = rep("sample", ncol(count_matrix)))
dds <- DESeqDataSetFromMatrix(countData = count_matrix, colData = col_data, design = ~1)

# Filter out low-count genes to reduce noise
dds <- dds[rowSums(counts(dds)) > 10, ]

# 4. Apply Variance Stabilizing Transformation (vst) 
# blind=TRUE is ideal for quality control / variance checking
vsd <- vst(dds, blind=TRUE, nsub=200) # manualy lowered after error: less than 'nsub' rows,
vst_mat <- assay(vsd)

# 5. Calculate row variances and select top N
rv <- rowVars(vst_mat)
select <- order(rv, decreasing = TRUE)[1:as.numeric(snakemake@params[["top_n"]])]
top_genes_mat <- vst_mat[select, ]

# 6. Z-score scaling by row (gene-wise scaling)
# scale() operates on columns, so we transpose, scale, and transpose back
scaled_mat <- t(scale(t(top_genes_mat)))

# 7. Plot and save to PDF
pdf(snakemake@output[["heatmap"]], width=8, height=10)
pheatmap(scaled_mat, 
         show_rownames = TRUE, 
         show_colnames = TRUE,
         main = paste0("Top ", snakemake@params[["top_n"]], " Most Variable Genes (Z-score)"),
         clustering_distance_rows = "euclidean",
         clustering_distance_cols = "euclidean",
         clustering_method = "complete")
dev.off()