import os
import pandas as pd

configfile: "config/config.yaml"
SAMPLES_SHORT = pd.read_csv(config["samples_short_read"], index_col="sample", sep='\t')
SAMPLES_LONG =  pd.read_csv(config["samples_long_read"], index_col="sample", sep='\t')
PROTEINS = pd.DataFrame(
	index=["amr_gene_A", "kinase_B"]
)

include: "rules/common.smk"
include: "rules/trimming.smk"
include: "rules/qc.smk"
include: "rules/decontamination.smk"
include: "rules/assembly.smk"
include: "rules/annotation.smk"
include: "rules/protein_phylogeny.smk"
include: "rules/resistance_prediciton.smk"
include: "rules/samtools.smk"

rule all:
	input:
		# de novo assembled and annotated genome for each sample. At least prediction of protein coding genes
		#expand("results/assembly/{sample}/secondary_assembly.fasta", sample=SAMPLES_SHORT.index),
		expand("results/annotation/{sample}/{sample}.gff", sample=SAMPLES_LONG.index),
		# established metrics
		#expand("results/assembly/{sample}/contiguity/", sample=SAMPLES_SHORT.index),
		#expand("results/denovo/{sample}/completness", sample=SAMPLES_SHORT.index),
		# core genome
		#"results/annotation/core/core_gene_alignment.aln",
		"results/phylo_tree/core_genome_tree.png",

		# antibiotic resistance
		# expand("results/card/{sample}", sample=SAMPLES_SHORT.index),
		# "results/card/overview",

		# QC
		# rule run_raw_qc
		"results/qc/multiqc_raw.html",

		# --- 2. Processed & Assembly QC Pipeline (FastQC Processed & Qualimap) ---
		# rule multiqc_all
		"results/qc/multiqc_all.html",

		# --- 3. Individual Qualimap runs (if you want them explicitly evaluated) ---
		expand("results/qc/qualimap/aligned/{sample}", sample=SAMPLES_SHORT.index),
		expand("results/qc/qualimap/filtered/{sample}", sample=SAMPLES_SHORT.index),

		# Protein sequences
		# expand("results/proteins/{protein}/orthologs", protein=PROTEINS),
		# expand("results/proteins/{protein}/msa", protein=PROTEINS),
		# expand("results/proteins/{protein}/phylo-tree", protein=PROTEINS),

		# AMR
		"results/card_amr_report/amr_merged.xlsx",

		# Protein Phylogeny
		plot_trees_for_succ_queries,

