import os
import pandas as pd

configfile: "config/config.yaml"
SAMPLES_SHORT = pd.read_csv(config["samples_short_read"], index_col="sample", sep='\t')
SAMPLES_LONG =  pd.read_csv(config["samples_long_read"], index_col="sample", sep='\t')
PROTEINS = []

include: "rules/common.smk"
include: "rules/trimming.smk"
include: "rules/process_samples.smk"
include: "rules/decontamination.smk"

rule all:
	input:
		# de novo assembled and annotated genome for each sample. At least prediction of protein coding genes
		expand("results/denovo/{sample}/genome", sample=SAMPLES_SHORT.index),
		expand("results/denovo/{sample}/annotation.gtf", sample=SAMPLES_SHORT.index),
		# established metrics
		expand("results/denovo/{sample}/contiguity", sample=SAMPLES_SHORT.index),
		expand("results/denovo/{sample}/completness", sample=SAMPLES_SHORT.index),
		# core genome
		"results/denovo/core_genome/genome",
		"results/denovo/core_genome/phylo-tree",

		# antibiotic resistance
		expand("results/card/{sample}", sample=SAMPLES_SHORT.index),
		"results/card/overview",

		# QC

		# Protein sequences
		expand("results/proteins/{protein}/orthologs", protein=PROTEINS),
		expand("results/proteins/{protein}/msa", protein=PROTEINS),
		expand("results/proteins/{protein}/phylo-tree", protein=PROTEINS),