import os
import pandas as pd

configfile: "config/config.yaml"

SAMPLES = pd.read_csv(config["samples"], index_col="sample", sep='\t')
GROUPS = SAMPLES['group'].unique()

REF_BASENAME = "reference"
# files at the end of analysis
rule all:
	input:
		expand ("results/stats/{sample}.stats", sample = SAMPLES.index ),
		expand("results/filtered/{sample}_mapping.bam", sample=SAMPLES.index),
		expand("results/groupwise/agg_group_{group}.tsv", group=GROUPS),
		"results/stats/merged.tsv"


include: "rules/bowtie.smk"
include: "rules/samtools.smk"

rule aggregate_stats:
	input:
		list_of_stats = lambda wildcards: expand(
					"results/stats/{sample}.stats", sample=SAMPLES.index)
	output:
		"results/stats/merged.tsv"
	script:
		"scripts/merge_stats.py"

rule grouped_stats:
	input:
		list_of_stats = lambda wildcards: expand(
					"results/stats/{sample}.stats", 
					sample=SAMPLES[SAMPLES['group'] == wildcards.group].index
				)	
	output:
		"results/groupwise/agg_group_{group}.tsv"
	script:
		"scripts/group_stats.py"
