import os
import pandas as pd

configfile: "config/config.yaml"

SAMPLES = pd.read_csv(config["samples"], index_col="sample", sep='\t')
GROUPS = SAMPLES['group'].unique()

REF_BASENAME = "reference"
# files at the end of analysis
rule all:
	input:
		expand ("results/stats/{sample}.stats", sample = SAMPLES.index ),
		expand("results/filtered/{sample}_mapping.bam", sample=SAMPLES.index),
		expand("results/groupwise/agg_group_{group}.tsv", group=GROUPS)

rule index_ref:
	input:
		ref = config["ref"]
	output:
		temp(multiext(REF_BASENAME, 
                 ".1.bt2", ".2.bt2", ".3.bt2", ".4.bt2", ".rev.1.bt2", ".rev.2.bt2"))
	log:
		"logs/index_ref/"+REF_BASENAME+".log"
	threads: 4
	conda:
		"envs/mapping.yaml"
	shell:
		"bowtie2-build --threads {threads} -f {input.ref} " + REF_BASENAME + " > {log} 2>&1" #<reference_in> <bt2_base>

rule map:
	input:
		r1 = lambda wildcards:SAMPLES.at[wildcards.sample,'fq1'],
		r2 = lambda wildcards:SAMPLES.at[wildcards.sample,'fq2'],
		ref_index = multiext(REF_BASENAME, 
		".1.bt2", ".2.bt2", ".3.bt2",          ".4.bt2", ".rev.1.bt2", ".rev.2.bt2")
	output:
		"results/sam/{sample}.sam"
	log:
		"logs/map/{sample}.log"
	threads: 4
	conda:
		"envs/mapping.yaml"
	shell:
		"bowtie2 --threads {threads} -x " + REF_BASENAME + " -1 {input.r1} -2 {input.r2} -S {output} 2>{log}"

rule convert:
	input:
		"results/sam/{sample}.sam"
	output:
		"results/bam/{sample}.bam"
	log:
		"logs/convert/{sample}.log"
	shell:
		"samtools view -bS {input} > {output} 2>{log}"

rule sort:
	input:
		"results/bam/{sample}.bam"
	output:
		"results/bam_sorted/{sample}.sorted.bam"
	log:
		"logs/sort/{sample}.log"
	shell:
		"samtools sort -o {output} {input} 2>{log}"

rule index:
	input:
		"results/bam_sorted/{sample}.sorted.bam"
	output:
		"results/bam_sorted/{sample}.sorted.bam.bai"
	log:
		"logs/index/{sample}.log"
	shell:
		"samtools index {input} 2>{log}"

rule calculate_stats:
	input:
		bam = "results/bam_sorted/{sample}.sorted.bam",
		bai = "results/bam_sorted/{sample}.sorted.bam.bai"
	output:
		"results/stats/{sample}.stats"
	log:
		"logs/stats/{sample}.log"
	shell:
		"samtools idxstats {input.bam} > {output} 2>{log}"



rule extract_mapping:
	input:
		bam = "results/bam_sorted/{sample}.sorted.bam",
		bai = "results/bam_sorted/{sample}.sorted.bam.bai"
	output:
		"results/filtered/{sample}_mapping.bam"
	log:
		"logs/filter/{sample}.log"
	shell:
		"samtools view -b {input.bam} NZ_AMKI01000040.1 NZ_AMKI01000041.1 > {output} 2>{log}"

rule grouped_stats:
	input:
		list_of_stats = lambda wildcards: expand(
					"results/stats/{sample}.stats", 
					sample=SAMPLES[SAMPLES['group'] == wildcards.group].index
				)	
	output:
		"results/groupwise/agg_group_{group}.tsv"
	script:
		"scripts/group_stats.py"