import os
import pandas as pd

configfile: "config/config.yaml"
SAMPLES = pd.read_csv(config["samples"], index_col="sample", sep='\t')
REF_BASENAME = "reference"
# files at the end of analysis
rule all:
	input:
		expand ("results/stats/{sample}.stats", sample = SAMPLES.index ),
		expand("results/filtered/{sample}_mapping.bam", sample=SAMPLES.index)

include: "rules/bowtie.smk"
include: "rules/samtools.smk"
