samples: "resources/samples.tsv"
reference: "/mnt/data/home/migrke113/ProjectBenedict/SequenceAnalysis_FUB/Project6/resources/ref/chr22_with_ERCC92.fa"
annotation: "/mnt/data/home/migrke113/ProjectBenedict/SequenceAnalysis_FUB/Project6/resources/ref/chr22_with_ERCC92.gtf"
top_n_variable: 10


analysis_options:
  skip_trimming: False
  skip_qualimap: False
  skip_fastQC: False
  precomputed_ref_index: "resources/star_genome"

bowtie2_params:
  ref_index_dir: "/resources/ref_index"


